// <auto-generated />
namespace yevgeller2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedFKforuserintoActivityDurationRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFKforuserintoActivityDurationRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201801121841146_Added FK for user into ActivityDurationRecords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
